### ISSUE TITLE
app:Validate and app:package Unexpected token › R in JSON at position 0 error

### ISSUE THREAD

**Issue by TosiRikhard** [zendesk/zcli#103]
## Expectations

  App validation in a CI CD devops pipeline to validate and package app

## Reality
![brave_OYH5DCML2D](https://user-images.githubusercontent.com/30078916/151147783-cc6e6d39-cb34-42e8-be3c-f8394510dfa2.png)

## Steps to Reproduce

1. Install devops ubuntu image in pipeline
2. Install zcli
3. add enviroment variables for zcli CI CD pipeline
4. run zcli apps:validate

### Issue details

- Command:  zcli apps validate 
- Version: 1.0.0-beta.15
- OS: ubuntu

There is no more detailed error to try to debug this issue further.

**Comment by osolliec** [comment]
I have the same issue, after successfully logging in with an API token.

**Comment by metasal1** [comment]
This happens when the **app id** is different in the **zcli.apps.config.json** from the app id in your instance.

Fastest way to resolve is to upload a new version of the app :- zcli apps:create
Manually remove the old version

Alternatively you can grab the app id from your instance and update your **zcli.apps.config.json** file with the correct number.
