### ISSUE TITLE
Ran apps:validate, got error: "Error: Authorization Failed, try logging in!"

### ISSUE THREAD

**Issue by chuck-wood** [zendesk/zcli#11]
## Expectations

Running `validate` command validates package.

## Reality

Got error message.

## Steps to Reproduce

1. Install zcli with `npm install @zendesk/zcli -g`
1. Attempt to validate app with `zcli apps:validate dev\download-all-attachments`

### Issue details

- Command: `zcli apps:validate dev\download-all-attachments`
- Version: @zendesk/zcli/1.0.0-beta.4 win32-x64 node-v12.13.1
- OS: Windows 10

I don't generally do the `zat create` and `zat update` workflow, so this app doesn't know about any Zendesk accounts. LMK if you need any further information. Thanks!

**Comment by sostopher** [comment]
Hey Chuck,

Thanks for the feedback. Currently, this is by design. The reason being is that we no longer include a gem (or module) inside the CLI package that does validation. This is because with ZAT this caused issues with being out of sync and sometimes not being accurate to the validations being done when uploading the app to the Marketplace.

This now requires authentication because it will use our server side authentication service to make sure that our validations are all being handled by the same place, and this endpoint is authenticated - not public. So while you don't have to connect to any specific account, you can log your ZCLI instance in to run the validations.

Chris

**Comment by chuck-wood** [comment]
Thanks Chris! I'm realizing I didn't even see the `login` command or I probably would have just done that :|

I have one app in the marketplace ("Download All Attachments") and have also built a few private apps.

**Comment by sostopher** [comment]
Hey Chuck,

I think we could improve that error message in that case to make it clearer how to authenticate 😄 and resolve it. 

Chris

**Comment by chuck-wood** [comment]
My process is pretty minimal, because I haven't built anything large and I don't build a lot of apps. I basically just use `zat=true` for testing (on my dev account), then `zat package` and install as a private app as a sanity check, and then that's about it. On the one marketplace app I have a python script that copies my README into the long description in translations (with the newlines escaped).
