### ISSUE TITLE
Installing ZCLI returns 404

### ISSUE THREAD

**Issue by gkatechis** [zendesk/zcli#44]
## Expectations

When running `npm install -g @zendesk/zcli`, I expected ZCLI to install nicely.

## Reality

Sadly, it did this:

`npm ERR! 404 Not Found - GET https://zdrepo.jfrog.io/zdrepo/api/npm/npm/@zendesk%2fzcli-core - not_found
npm ERR! 404
npm ERR! 404  '@zendesk/zcli-core@^1.0.0-beta.4' is not in the npm registry.`

![zcli 404](https://user-images.githubusercontent.com/19415268/112062701-42c69880-8b2e-11eb-8cc2-0a9fe9613add.png)

## Steps to Reproduce

1. Run `npm install -g @zendesk/zcli`
2. Be sad :(

### Issue details

- Command: `npm install -g @zendesk/zcli`
- Version: beta 8...I think?
- OS: MacOS 10.15.7

**Comment by sarmadsangi** [comment]
@gkatechis This issue happens because we have a stale/old version of zcli in artifactory. You must have artifactory registry in your npmrc and its trying to pull from there instead of npm registry.

I have requested artifactory registry admins to remove this from artifactory to avoid this issue for internal users of zcli, in a meanwhile you can try removing artifactory registry from your npmrc just before installing.

**Comment by gkatechis** [comment]
Thanks Sarmad, you were correct! I removed the registry from .npmrc and it installed successfully. Thanks for the help!

**Comment by sarmadsangi** [comment]
@gkatechis this should now work regardless of npmrc modification.
